name: OptimizationUtils
version: '${version}'
main: com.epicplayera10.optimizationutils.OptimizationUtils
api-version: '1.16'
authors: [EpicPlayerA10]
website: https://fanth.pl
description: A minecraft plugin with some useful optimization utils.
permissions:
  optimizationutils.updatechecker:
    description: Allows players to receive update notifications
    default: op
